Service_Manpower/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('home/', include('home.urls')),
    path('', include('home.urls')),
    path('users/', include('users.urls', namespace= 'users')),
    path('bookings/', include('bookings.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls  import path
from . import views

app_name = 'home_module'
urlpatterns = [
    path('', views.home , name = 'home' ),
    # path('bookings/', views.bookings, name = 'bookings'),
    # path('profile/', views.profile, name = 'profile'),


]

users/urls.py
from django.contrib import admin
from django.urls  import path
from users import views
from django.contrib.auth.views import LogoutView

# from .views import CustomLoginView

app_name = 'users'
urlpatterns = [
    path('profile/', views.profile, name = 'profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    # path('userlist', views.user_list, name='user_list'),
    path('signup/', views.signup, name='signup'),
    path('signup/professional/', views.professional_signup, name='professional_signup'),

]

users/models.py
# users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    

    def __str__(self):
        return self.full_name

class ManpowerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.TextField()
    phone = models.CharField(max_length=15)
    skill = models.CharField(max_length=100)
    experience_years = models.PositiveIntegerField()
    photo = models.ImageField(upload_to='manpower/photos/', blank=True, null=True)
    citizenship_front = models.ImageField(upload_to='manpower/citizenship/front/', blank=True, null=True)
    citizenship_back = models.ImageField(upload_to='manpower/citizenship/back/', blank=True, null=True)

    def __str__(self):
        return self.name

users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from .models import UserProfile, ManpowerProfile
from django.contrib.auth import get_user_model, authenticate

class UserSignupForm(UserCreationForm):
    username = None
    full_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Full Name'}))

    phone_number = forms.CharField(max_length=10, required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Phone Number'}))

    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control','placeholder': 'Email Address'
    }))

    class Meta:
        model = User
        fields = ('full_name', 'email', 'phone_number', 'password1', 'password2')

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({'class':'form-control', 'placeholder':'Password'})
        self.fields['password2'].widget.attrs.update({'class':'form-control', 'placeholder':'Confirm Password'})


    def clean_phone_number(self):
        phone = self.cleaned_data['phone_number']
        if not phone.isdigit() or len(phone) < 10:
            raise forms.ValidationError("Enter a valid phone number (at least 10 digits).")
        return phone
    
User = get_user_model()
class LoginForm(forms.Form):
    username = None
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control','placeholder': 'Email Address'
    }))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control','placeholder': 'Password'
    }))
    
    def clean(self):
        cleaned_data =  super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        
        if email and password:
             try:
                 user = User.objects.get(email = email)
                 user = authenticate(username = user.username, password = password)
                 if user is None:
                     raise forms.ValidationError("Invalid credentials")
                 self.user = user
             except User.DoesNotExist:
                 raise forms.ValidationError("Invalid Credentials")
             
        return cleaned_data


class ManpowerSignupForm(UserCreationForm):
    name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}))
    district = forms.CharField(max_length=100, required=True, label="District", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'District'}))
    local_address = forms.CharField(max_length=100, required=True, label="Local Address", widget=forms.TextInput(attrs={
        'placeholder': 'e.g. Ward No. 5, Budhanilkantha',
        'class': 'form-control'
    }))
    phone = forms.CharField(max_length=15, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone'}))
    skill = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Skills'}))
    experience_years = forms.IntegerField(min_value=0, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'experience'}))
    photo = forms.ImageField(required=False, )
    citizenship_front = forms.ImageField(required=False)
    citizenship_back = forms.ImageField(required=False)
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))

    class Meta:
        model = User
        fields = (
             'email', 'name', 
            'phone', 'skill', 'district', 'local_address','experience_years',
            'photo', 'citizenship_front', 'citizenship_back',
            
        )

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if not phone.isdigit() or len(phone) < 10:
            raise forms.ValidationError("Enter a valid phone number (at least 10 digits).")
        return phone

    

# # List of all 77 districts of Nepal
# DISTRICT_CHOICES = [
#     ('Bhojpur', 'Bhojpur'),
#     ('Dhankuta', 'Dhankuta'),
#     ('Ilam', 'Ilam'),
#     ('Jhapa', 'Jhapa'),
#     ('Khotang', 'Khotang'),
#     ('Morang', 'Morang'),
#     ('Okhaldhunga', 'Okhaldhunga'),
#     ('Panchthar', 'Panchthar'),
#     ('Sankhuwasabha', 'Sankhuwasabha'),
#     ('Solukhumbu', 'Solukhumbu'),
#     ('Sunsari', 'Sunsari'),
#     ('Taplejung', 'Taplejung'),
#     ('Terhathum', 'Terhathum'),
#     ('Udayapur', 'Udayapur'),
#     ('Bara', 'Bara'),
#     ('Parsa', 'Parsa'),
#     ('Rautahat', 'Rautahat'),
#     ('Saptari', 'Saptari'),
#     ('Sarlahi', 'Sarlahi'),
#     ('Siraha', 'Siraha'),
#     ('Dhanusha', 'Dhanusha'),
#     ('Mahottari', 'Mahottari'),
#     ('Bhaktapur', 'Bhaktapur'),
#     ('Kathmandu', 'Kathmandu'),
#     ('Lalitpur', 'Lalitpur'),
#     ('Chitwan', 'Chitwan'),
#     ('Makwanpur', 'Makwanpur'),
#     ('Ramechhap', 'Ramechhap'),
#     ('Dolakha', 'Dolakha'),
#     ('Sindhuli', 'Sindhuli'),
#     ('Sindhupalchok', 'Sindhupalchok'),
#     ('Kavrepalanchok', 'Kavrepalanchok'),
#     ('Nuwakot', 'Nuwakot'),
#     ('Rasuwa', 'Rasuwa'),
#     ('Dhading', 'Dhading'),
#     ('Gorkha', 'Gorkha'),
#     ('Kaski', 'Kaski'),
#     ('Lamjung', 'Lamjung'),
#     ('Manang', 'Manang'),
#     ('Mustang', 'Mustang'),
#     ('Myagdi', 'Myagdi'),
#     ('Nawalpur', 'Nawalpur'),
#     ('Parbat', 'Parbat'),
#     ('Syangja', 'Syangja'),
#     ('Tanahun', 'Tanahun'),
#     ('Baglung', 'Baglung'),
#     ('Kapilvastu', 'Kapilvastu'),
#     ('Palpa', 'Palpa'),
#     ('Rupandehi', 'Rupandehi'),
#     ('Arghakhanchi', 'Arghakhanchi'),
#     ('Gulmi', 'Gulmi'),
#     ('Dang', 'Dang'),
#     ('Banke', 'Banke'),
#     ('Bardiya', 'Bardiya'),
#     ('Dailekh', 'Dailekh'),
#     ('Dolpa', 'Dolpa'),
#     ('Humla', 'Humla'),
#     ('Jajarkot', 'Jajarkot'),
#     ('Jumla', 'Jumla'),
#     ('Kalikot', 'Kalikot'),
#     ('Mugu', 'Mugu'),
#     ('Rukum East', 'Rukum East'),
#     ('Rukum West', 'Rukum West'),
#     ('Salyan', 'Salyan'),
#     ('Surkhet', 'Surkhet'),
#     ('Achham', 'Achham'),
#     ('Baitadi', 'Baitadi'),
#     ('Bajhang', 'Bajhang'),
#     ('Bajura', 'Bajura'),
#     ('Dadeldhura', 'Dadeldhura'),
#     ('Darchula', 'Darchula'),
#     ('Doti', 'Doti'),
#     ('Kanchanpur', 'Kanchanpur'),
#     ('Kailali', 'Kailali'),
# ]

users/views.py
# users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login ,get_user_model
from .forms import UserSignupForm, LoginForm, ManpowerSignupForm
from users.models import UserProfile, ManpowerProfile
from home import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView


@login_required
def profile(request):
    user = request.user
    user_profile = UserProfile.objects.get(user=user) 
    return render(request, 'users/profile.html', {'user_profile': user_profile})
    

# def signup_choice(request):
#     return render(request, 'users/signup_choice.html')
User = get_user_model()
def signup(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit= False)
            user.username = form.cleaned_data['email'].split('@')[0]+ str(User.objects.count())
            user.save()
            UserProfile.objects.create(
                user=user,
                full_name=form.cleaned_data['full_name'],
                phone_number=form.cleaned_data['phone_number']
            )
            return redirect('users:login')
    else:
        form = UserSignupForm()
    return render(request, 'users/html', {'form': form})

def professional_signup(request):
    if request.method == 'POST':
        form = ManpowerSignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            ManpowerProfile.objects.create(
                user=user,
                name=form.cleaned_data['name'],
                address=form.cleaned_data['address'],
                phone=form.cleaned_data['phone'],
                skill=form.cleaned_data['skill'],
                experience_years=form.cleaned_data['experience_years'],
                photo=form.cleaned_data['photo'],
                citizenship_front=form.cleaned_data['citizenship_front'],
                citizenship_back=form.cleaned_data['citizenship_back']
            )
            return redirect('users:login')
    else:
        form = ManpowerSignupForm()
    return render(request, 'users/professional_signup.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            auth_login(request, form.user)
            return redirect('home_module:home')
           
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form':form})

class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, "You have been logged out successfully.")
        return super().dispatch(request, *args, **kwargs)
    template_name='users/login.html'

users/templates/users/base.html
<!-- users/templates/users/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    
  <!-- Font Awesome -->
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
  />
    <!-- <style>
        body {
            font-family: Arial, sans-serif;
            background: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            /* max-width: 600px; */
            margin: 50px;
            padding: 20px;
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            text-align: center;
            color: #333;
        }
        .form-group {
            margin-bottom: 15px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            color: #555;
        }
        input, textarea, select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-sizing: border-box;
        }
        button {
            width: 100%;
            padding: 12px;
            background: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background 0.3s;
        }
        button:hover {
            background: #0056b3;
        }
        .error {
            color: red;
            font-size: 0.9em;
        }
        .choice-btn {
            display: inline-block;
            width: 45%;
            margin: 10px;
            text-align: center;
        }
        @media (max-width: 600px) {
            .container {
                margin: 20px;
                padding: 15px;
            }
            .choice-btn {
                width: 100%;
            }
        }
    </style> -->
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

users/templates/users/login.html
{% load static %}
<!-- {% block title %}Login{% endblock %} -->

{% block content %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap Icons -->
<link
href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
rel="stylesheet"
/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% if messages %}
   <div class="container ps-2">
    <div class="messages-container">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
   </div>
{% endif %}
<div class="container-fluid login-container p-0">
    <div class="column ">
        <!-- Calendar Background Side -->
        <div class="col-lg-12 calendar-bg">
            <div class="calendar-content">
                <div class="calendar-header">PROFESSIONAL BOOKING PLATFORM</div>
                <div>
                    <h1 class="calendar-title">Book a Professional</h1>
                    <p class="calendar-subtitle">Schedule appointments with experts in minutes</p>
                </div>
            </div>
        </div>
        
        <div class="col-lg-12 login-form">
            <div class="form-wrapper">
                <h2 class="form-title">Welcome Back</h2>
                
                <form method="post" class="django-form needs-validation" novalidate>
                    {% csrf_token %}
                    
                    {% for field in form %}
                        <div class="form-group mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">
                                {% if field.name == 'email' %}
                                    <i class="bi bi-envelope me-2"></i>
                                {% elif field.name == 'password' %}
                                    <i class="bi bi-lock me-2"></i>
                                {% endif %}
                                {{ field.label }}
                            </label>
                            {{ field }}
                            {% if field.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ field.errors|join:", " }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    
                    <button type="submit" class="btn btn-login w-50">Login</button>
                    
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger mt-3">
                            {{ form.non_field_errors|join:", " }}
                        </div>
                    {% endif %}
                    
                    <p class="text-center mt-3">
                        Don't have an account? 
                        <a href="{% url 'users:signup' %}" class="text-primary fw-bold">Sign Up</a>
                    </p>
                </form>
            </div>
        </div>        
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
<!-- Add this script for validation styling -->
<script>
(function() {
    'use strict';
    window.addEventListener('load', function() {
        // Fetch all forms we want to apply custom validation styles to
        var forms = document.getElementsByClassName('needs-validation');
        
        // Loop over them and prevent submission
        Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
            }, false);
        });
    }, false);
})();
</script>

<!-- Add this to your login.css -->
<style>
    .was-validated .form-control:invalid {
        border-color: #dc3545;
        padding-right: calc(1.5em + 0.75rem);
        background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 12 12' width='12' height='12' fill='none' stroke='%23dc3545'%3e%3ccircle cx='6' cy='6' r='4.5'/%3e%3cpath stroke-linejoin='round' d='M5.8 3.6h.4L6 6.5z'/%3e%3ccircle cx='6' cy='8.2' r='.6' fill='%23dc3545' stroke='none'/%3e%3c/svg%3e");
        background-repeat: no-repeat;
        background-position: right calc(0.375em + 0.1875rem) center;
        background-size: calc(0.75em + 0.375rem) calc(0.75em + 0.375rem);
    }
    
    .was-validated .form-control:invalid:focus {
        border-color: #dc3545;
        box-shadow: 0 0 0 0.25rem rgba(220, 53, 69, 0.25);
    }
    
    .invalid-feedback {
        display: none;
        width: 100%;
        margin-top: 0.25rem;
        font-size: 0.875em;
        color: #dc3545;
    }
    
    .was-validated .form-control:invalid ~ .invalid-feedback {
        display: block;
    }
</style>
{% endblock %}

users/templates/users/signup_choice.html
{% extends 'users/base.html' %}
{% block title %}Choose Signup Type{% endblock %}
{% block content %}
{% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Custom CSS -->
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f5f7fa;
        }
        .left-section {
            background-size: cover;
            background-position: center;
            min-height: 100vh;
            color: #1e3a8a;
        }
        .left-section .header-text {
            font-size: 2.5rem;
            font-weight: 700;
            line-height: 1.2;
        }
        .left-section .highlight {
            border: 2px solid #f97316;
            border-radius: 10px;
            padding: 0 5px;
            display: inline-block;
        }
        .right-section {
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2rem;
        }
        .choice-container {
            max-width: 400px;
            width: 100%;
        }
        .choice-container h2 {
            font-size: 1.8rem;
            font-weight: 700;
            color: #1e3a8a;
        }
        .choice-container p {
            color: #6b7280;
        }
        .role-btn {
            border: 1px solid #d1d5db;
            border-radius: 8px;
            padding: 10px;
            text-align: center;
            font-size: 0.9rem;
            font-weight: 500;
            color: #6b7280;
            transition: all 0.3s ease;
            text-decoration: none;
        }
        .role-btn:hover {
            border-color: #2563eb;
            color: #2563eb;
        }
    </style>

    <div class="container-fluid p-0">
        <div class="row g-0 min-vh-100">
            <!-- Left Section -->
            <div class="col-md-6 left-section d-flex align-items-start p-5">
                <div>
                    <div class="d-flex align-items-center mb-4">
                        <svg class="w-6 h-6 text-blue-600 me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7m-9 9v-6h6v6m-6-6h6"></path>
                        </svg>
                        <span class="text-blue-600 fw-semibold fs-5">ProConnect</span>
                    </div>
                    <h1 class="header-text">
                        Simplify <span class="highlight">Scheduling</span><br>for Professionals<br>and Users
                    </h1>
                </div>
            </div>

            <!-- Right Section -->
            <div class="col-md-6 right-section">
                <div class="choice-container">
                    <h2>Sign Up As</h2>
                    <p class="mb-4">Choose your category to access tailored features and resources</p>
                    <div class="d-flex gap-3">
                        <a href="{% url 'users:signup' %}" class="role-btn flex-fill d-flex align-items-center justify-content-center">
                            <svg class="w-5 h-5 me-2 d-inline-block" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                            </svg>
                            User
                        </a>
                        <a href="{% url 'users:professional_signup' %}" class="role-btn flex-fill d-flex align-items-center justify-content-center">
                            <svg class="w-5 h-5 me-2 d-inline-block" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                            </svg>
                            Professional
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

{% endblock %}